window.STARSHIP_DATA = [
  {
    "id": "e32d375f-0d6e-4e54-b4f2-2b49db657fca",
    "mission": "Starship | Integrated Flight Test",
    "date": "04/20/2023",
    "status": "Launch Failure",
    "rocket": "Starship",
    "version": "Starship V1",
    "variant": "V1",
    "pad": "Orbital Launch Pad 1",
    "site": "SpaceX Starbase, TX, USA",
    "missionDetail": "Integrated Flight Test",
    "description": "Maiden flight of the two-stage Starship launch vehicle. The booster was supposed to separate 170 seconds into flight and return to land approximately 32 km off the shore in the Gulf of Mexico. The second stage would have followed a suborbital trajectory and performed an unpowered splashdown approximately 100 km off the northwest coast of Kauai (Hawaii). A launch failure was experienced before stage separation.",
    "failureReason": "After liftoff, the vehicle sustained fires from leaking propellant in the aft end of the Super Heavy booster, severing connection with the vehicle’s primary flight computer. This led to a loss of communications to most of the booster engines and eventually control of the vehicle. After the second stage failed to separate from the first stage, the vehicle reached an apogee of ~39km before tumbling downwards until the flight termination system was activated.\r\n\r\nUnexpected severe damage was also imparted on the launch pad.",
    "landingSite": "Pacific Ocean",
    "orbit": "Sub",
    "booster": "Booster 7",
    "ship": "Ship 24",
    "shipFlightNum": "S24"
  },
  {
    "id": "04b91bb8-38a7-4868-b025-4bbe05d1fbfe",
    "mission": "Starship | Integrated Flight Test 2",
    "date": "11/18/2023",
    "status": "Launch was a Partial Failure",
    "rocket": "Starship",
    "version": "Starship V1",
    "variant": "V1",
    "pad": "Orbital Launch Pad 1",
    "site": "SpaceX Starbase, TX, USA",
    "missionDetail": "Integrated Flight Test 2",
    "description": "Second test flight of the two-stage Starship launch vehicle. The booster is expected to separate 170 seconds into flight and return to land approximately 32 km off the shore in the Gulf of Mexico. The second stage will follow a suborbital trajectory and perform an unpowered splashdown approximately 100 km off the northwest coast of Kauai (Hawaii).",
    "failureReason": "Flight termination system activated on Starship after T+8 minutes, seconds before planned SECO, due to a leak of liquid oxygen causing a combustion event and fires which led to a loss of communication. Booster was destroyed during the boost-back burn. most likely due to a filter blockage on a liquid oxygen line supplying the engines. Most planned primary objectives achieved.",
    "landingSite": "Pacific Ocean",
    "orbit": "Sub",
    "booster": "Booster 9",
    "ship": "Ship 25",
    "shipFlightNum": "S25"
  },
  {
    "id": "c0d90c60-4961-470a-a6d7-804b3bf4b012",
    "mission": "Starship | Integrated Flight Test 3",
    "date": "03/14/2024",
    "status": "Launch Successful",
    "rocket": "Starship",
    "version": "Starship V1",
    "variant": "V1",
    "pad": "Orbital Launch Pad 1",
    "site": "SpaceX Starbase, TX, USA",
    "missionDetail": "Integrated Flight Test 3",
    "description": "Third test flight of the two-stage Starship launch vehicle.",
    "failureReason": "",
    "landingSite": "Indian Ocean",
    "orbit": "Sub",
    "booster": "Booster 10",
    "ship": "Ship 28",
    "shipFlightNum": "S28"
  },
  {
    "id": "2b1b756f-7207-4781-a874-aed61b38463d",
    "mission": "Starship | Integrated Flight Test 4",
    "date": "06/06/2024",
    "status": "Launch Successful",
    "rocket": "Starship",
    "version": "Starship V1",
    "variant": "V1",
    "pad": "Orbital Launch Pad 1",
    "site": "SpaceX Starbase, TX, USA",
    "missionDetail": "Integrated Flight Test 4",
    "description": "Fourth test flight of the two-stage Starship launch vehicle.",
    "failureReason": "",
    "landingSite": "Indian Ocean",
    "orbit": "Sub",
    "booster": "Booster 11",
    "ship": "Ship 29",
    "shipFlightNum": "S29"
  },
  {
    "id": "83ba001e-9bca-48ac-84cb-ccea96bfe9c1",
    "mission": "Starship | Integrated Flight Test 5",
    "date": "10/13/2024",
    "status": "Launch Successful",
    "rocket": "Starship",
    "version": "Starship V1",
    "variant": "V1",
    "pad": "Orbital Launch Pad 1",
    "site": "SpaceX Starbase, TX, USA",
    "missionDetail": "Integrated Flight Test 5",
    "description": "Fifth test flight of the two-stage Starship launch vehicle.",
    "failureReason": "",
    "landingSite": "Indian Ocean",
    "orbit": "Sub",
    "booster": "Booster 12",
    "ship": "Ship 30",
    "shipFlightNum": "S30"
  },
  {
    "id": "da9a0172-062c-4b29-81d8-acf777d3777f",
    "mission": "Starship | Integrated Flight Test 6",
    "date": "11/19/2024",
    "status": "Launch Successful",
    "rocket": "Starship",
    "version": "Starship V1",
    "variant": "V1",
    "pad": "Orbital Launch Pad 1",
    "site": "SpaceX Starbase, TX, USA",
    "missionDetail": "Integrated Flight Test 6",
    "description": "Sixth test flight of the two-stage Starship launch vehicle.",
    "failureReason": "",
    "landingSite": "Indian Ocean",
    "orbit": "Sub",
    "booster": "Booster 13",
    "ship": "Ship 31",
    "shipFlightNum": "S31"
  },
  {
    "id": "c5566f6e-606e-4250-b8f4-477c5d82c798",
    "mission": "Starship | Flight 7",
    "date": "01/16/2025",
    "status": "Launch Failure",
    "rocket": "Starship",
    "version": "Starship V2",
    "variant": "V2",
    "pad": "Orbital Launch Pad 1",
    "site": "SpaceX Starbase, TX, USA",
    "missionDetail": "Flight 7",
    "description": "Seventh test flight of the two-stage Starship launch vehicle.",
    "failureReason": "Ship 33 lost all 6 engines gradually late in ascent and was observed to have self-destructed.",
    "landingSite": "Indian Ocean",
    "orbit": "Sub",
    "booster": "Booster 14",
    "ship": "Ship 33",
    "shipFlightNum": "S33"
  },
  {
    "id": "a2b94add-d1e8-4b1d-9f25-afe7904580d3",
    "mission": "Starship | Flight 8",
    "date": "03/06/2025",
    "status": "Launch Failure",
    "rocket": "Starship",
    "version": "Starship V2",
    "variant": "V2",
    "pad": "Orbital Launch Pad 1",
    "site": "SpaceX Starbase, TX, USA",
    "missionDetail": "Flight 8",
    "description": "Eighth test flight of the two-stage Starship launch vehicle.",
    "failureReason": "Ship 34 lost 4 out of 6 Raptors at around T+8:00 and entered unrecoverable roll.",
    "landingSite": "Indian Ocean",
    "orbit": "Sub",
    "booster": "Booster 15",
    "ship": "Ship 34",
    "shipFlightNum": "S34"
  },
  {
    "id": "ef9b458b-bebf-4eb6-b970-8d77998616f3",
    "mission": "Starship | Flight 9",
    "date": "05/27/2025",
    "status": "Launch Failure",
    "rocket": "Starship",
    "version": "Starship V2",
    "variant": "V2",
    "pad": "Orbital Launch Pad 1",
    "site": "SpaceX Starbase, TX, USA",
    "missionDetail": "Flight 9",
    "description": "9th test flight of the two-stage Starship launch vehicle.",
    "failureReason": "",
    "landingSite": "Indian Ocean",
    "orbit": "Sub",
    "booster": "Booster 14",
    "ship": "Ship 35",
    "shipFlightNum": "S35"
  },
  {
    "id": "fc1dafd8-bcb0-4e77-8ba9-2d03134f04e4",
    "mission": "Starship | Flight 10",
    "date": "08/26/2025",
    "status": "Launch Successful",
    "rocket": "Starship",
    "version": "Starship V2",
    "variant": "V2",
    "pad": "Orbital Launch Pad 1",
    "site": "SpaceX Starbase, TX, USA",
    "missionDetail": "Flight 10",
    "description": "10th test flight of the two-stage Starship launch vehicle.",
    "failureReason": "",
    "landingSite": "Indian Ocean",
    "orbit": "Sub",
    "booster": "Booster 16",
    "ship": "Ship 37",
    "shipFlightNum": "S37"
  },
  {
    "id": "41068e09-4097-448f-ac7c-421c19b6aab9",
    "mission": "Starship | Flight 11",
    "date": "10/13/2025",
    "status": "Launch Successful",
    "rocket": "Starship",
    "version": "Starship V2",
    "variant": "V2",
    "pad": "Orbital Launch Pad 1",
    "site": "SpaceX Starbase, TX, USA",
    "missionDetail": "Flight 11",
    "description": "11th test flight of the two-stage Starship launch vehicle.",
    "failureReason": "",
    "landingSite": "Indian Ocean",
    "orbit": "Sub",
    "booster": "Booster 15",
    "ship": "Ship 38",
    "shipFlightNum": "S38"
  },
  {
    "id": "ed83366c-872c-4484-97c1-bc74832304fc",
    "mission": "Starship | Flight 12",
    "date": "05/22/2026",
    "status": "Launch Successful",
    "rocket": "Starship",
    "version": "Starship V3",
    "variant": "V3",
    "pad": "Orbital Launch Pad 2",
    "site": "SpaceX Starbase, TX, USA",
    "missionDetail": "Flight 12",
    "description": "12th test flight of the two-stage Starship launch vehicle. Maiden Flight of Starship V3.\r\n\r\nThe flight test’s primary goal will be to demonstrate each of these new pieces in the flight environment for the first time, with each element of the Starship architecture featuring significant redesigns to enable full and rapid reuse that incorporate learnings from years of development and test.\r\n\r\nThe Starship upper stage will target multiple in-space and reentry objectives, including a payload deployment of 20 Starlink simulators, similar in size to next-generation Starlink V3 satellites, and two specially modified Starlink satellites. The two modified satellites will test hardware planned for Starlink V3 and will attempt to scan Starship’s heat shield and transmit imagery down to operators to test methods of analyzing Starship’s heat shield readiness for return to launch site on future missions. Several tiles on Starship have been painted white to simulate missing tiles and serve as imaging targets in the test. The Starlink simulators will be on the same suborbital trajectory as Starship. A relight of a single Raptor engine while in space is also planned.\r\n\r\nFor Starship entry, a single heat shield tile has been intentionally removed to measure the aerodynamic load differences on adjacent tiles when there is a tile missing. Finally, the ship will perform experimental actions tested on previous flight tests, including a maneuver to intentionally stress the structural limits of the vehicle’s rear flaps and a dynamic banking maneuver to mimic the trajectory that future missions returning to Starbase will fly.",
    "failureReason": "",
    "landingSite": "Indian Ocean",
    "orbit": "Sub",
    "booster": "Booster 19",
    "ship": "Ship 39",
    "shipFlightNum": "S39"
  },
  {
    "id": "ac897b9f-44d2-4ff4-8416-1a0a076e98a2",
    "mission": "Starship | Flight 13",
    "date": "07/24/2026",
    "status": "Launch Successful",
    "rocket": "Starship",
    "version": "Starship V3",
    "variant": "V3",
    "pad": "Orbital Launch Pad 2",
    "site": "SpaceX Starbase, TX, USA",
    "missionDetail": "Flight 13",
    "description": "13th test flight of the two-stage Starship launch vehicle. Second flight of Starship V3.\r\n\r\nFor the first time, Starship will carry 20 V3 Starlink satellites to space, which will extend solar arrays and antennas and will attempt to connect with ground stations in South Africa and the larger Starlink constellation via high-capacity lasers. \r\n\r\n6 of the satellites have been modified with a suite of cameras to scan Starship’s heat shield and transmit imagery down to operators to continue testing methods of analyzing Starship’s heat shield readiness for return to launch site on future missions. Several tiles on Starship have been painted white to simulate missing tiles and serve as imaging targets in the test.",
    "failureReason": "",
    "landingSite": "Indian Ocean",
    "orbit": "Sub",
    "booster": "Booster 20",
    "ship": "Ship 40",
    "shipFlightNum": "S40"
  }
];